/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import model.Service;
import model.ServiceCatalog;
/**
 *
 * @author Administrator
 */
public class ServiceAddPanel extends javax.swing.JPanel {

    private ServiceCatalog serviceCatalog;
    
    public ServiceAddPanel() {
        initComponents();
        serviceCatalog = ServiceCatalog.getInstance();
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblServiceID = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMechanic = new javax.swing.JLabel();
        lblMechanicName = new javax.swing.JLabel();
        lblServiceDuration = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        txtServiceType = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtMechanic = new javax.swing.JTextField();
        txtMechanicName = new javax.swing.JTextField();
        txtServiceDuration = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreateService = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("Services");

        lblServiceID.setText("Service ID：");

        lblServiceType.setText("Service Type：");

        lblCost.setText("Cost：");

        lblMechanic.setText("Mechanic‘s Name：");

        lblMechanicName.setText("Mechanic’s Name");

        lblServiceDuration.setText("Service Duration：");

        txtServiceID.addActionListener(this::txtServiceIDActionPerformed);

        txtServiceType.addActionListener(this::txtServiceTypeActionPerformed);

        btnBack.setText("<< Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnCreateService.setText("Create Service");
        btnCreateService.addActionListener(this::btnCreateServiceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblServiceID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblServiceType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMechanic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMechanicName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblServiceDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtServiceID)
                            .addComponent(txtServiceType)
                            .addComponent(txtCost)
                            .addComponent(txtMechanic)
                            .addComponent(txtMechanicName)
                            .addComponent(txtServiceDuration, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateService)
                    .addComponent(jLabel1))
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceID)
                    .addComponent(txtServiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceType)
                    .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanic)
                    .addComponent(txtMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanicName)
                    .addComponent(txtMechanicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDuration)
                    .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnCreateService)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceIDActionPerformed

    private void txtServiceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceTypeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to main interface
        Container parent = this.getParent();
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, "welcome");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed
        // Validate all fields are not empty
        if (txtServiceID.getText().trim().isEmpty() || 
            txtServiceType.getText().trim().isEmpty() || 
            txtCost.getText().trim().isEmpty() || 
            txtMechanicName.getText().trim().isEmpty() || 
            txtServiceDuration.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "All fields are required and cannot be empty!", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Get and validate input data
            int serviceId = Integer.parseInt(txtServiceID.getText().trim());
            String serviceType = txtServiceType.getText().trim();
            double cost = Double.parseDouble(txtCost.getText().trim());
            String mechanicName = txtMechanicName.getText().trim();
            short serviceDuration = Short.parseShort(txtServiceDuration.getText().trim());
            
            // Validate data types and ranges
            if (serviceId <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "Service ID must be a positive integer!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (cost < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Cost cannot be negative!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (serviceDuration <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "Service duration must be positive!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if service ID already exists
            if (serviceCatalog.findServiceById(serviceId) != null) {
                JOptionPane.showMessageDialog(this, 
                    "Service ID already exists! Please use a different ID.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create service object
            Service service = new Service(serviceId, serviceType, cost, mechanicName, serviceDuration);
            
            // Add to service catalog
            serviceCatalog.addService(service);
            
            // Display success message
            JOptionPane.showMessageDialog(this, 
                "Service created successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear form
            clearForm();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please enter valid number format!\n" +
                "Service ID: integer\n" +
                "Cost: decimal\n" +
                "Service Duration: integer", 
                "Input Format Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateServiceActionPerformed
    
    /**
     * Clear form
     */
    private void clearForm() {
        txtServiceID.setText("");
        txtServiceType.setText("");
        txtCost.setText("");
        txtMechanic.setText("");
        txtMechanicName.setText("");
        txtServiceDuration.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMechanic;
    private javax.swing.JLabel lblMechanicName;
    private javax.swing.JLabel lblServiceDuration;
    private javax.swing.JLabel lblServiceID;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMechanic;
    private javax.swing.JTextField txtMechanicName;
    private javax.swing.JTextField txtServiceDuration;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
