/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import model.Owner;
import model.Vehicle;
import model.Service;
import model.VehicleDirectory;
import model.ServiceCatalog;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Administrator
 */
public class VehicleAddPanel extends javax.swing.JPanel {

    private VehicleDirectory vehicleDirectory;
    private ServiceCatalog serviceCatalog;
    
    /**
     * Creates new form VehicleAddPanel
     */
    public VehicleAddPanel() {
        initComponents();
        vehicleDirectory = VehicleDirectory.getInstance();
        serviceCatalog = ServiceCatalog.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOwnerID = new javax.swing.JLabel();
        lblOwnerFirstName = new javax.swing.JLabel();
        lblOwnerLastName = new javax.swing.JLabel();
        lblServiceDate = new javax.swing.JLabel();
        txtOwnerID = new javax.swing.JTextField();
        txtOwnerFirstName = new javax.swing.JTextField();
        txtOwnerLastName = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        VehicleArea = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblVehicleID = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblRegistration = new javax.swing.JLabel();
        lblServiceOpted = new javax.swing.JLabel();
        txtVehicleID = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtRegistration = new javax.swing.JTextField();
        txtServiceOpted = new javax.swing.JTextField();
        btnRegisterService = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("Owner Details");

        lblOwnerID.setText("Owner ID:");

        lblOwnerFirstName.setText("Owner First Name:");

        lblOwnerLastName.setText("Owner Last Name:");

        lblServiceDate.setText("Service Date:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        VehicleArea.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setText("Vehicle Details");

        lblVehicleID.setText("Vehicle ID：");

        lblMake.setText("Make:");

        lblModel.setText("Model:");

        lblRegistration.setText("Registration Number:");

        lblServiceOpted.setText("Service Opted:");

        javax.swing.GroupLayout VehicleAreaLayout = new javax.swing.GroupLayout(VehicleArea);
        VehicleArea.setLayout(VehicleAreaLayout);
        VehicleAreaLayout.setHorizontalGroup(
            VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleAreaLayout.createSequentialGroup()
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehicleAreaLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehicleID)
                            .addComponent(lblMake)
                            .addComponent(lblModel)
                            .addComponent(lblRegistration)
                            .addComponent(lblServiceOpted))
                        .addGap(63, 63, 63)
                        .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehicleID)
                            .addComponent(txtMake)
                            .addComponent(txtModel)
                            .addComponent(txtRegistration)
                            .addComponent(txtServiceOpted, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(VehicleAreaLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        VehicleAreaLayout.setVerticalGroup(
            VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleAreaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleID)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistration)
                    .addComponent(txtRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(VehicleAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiceOpted)
                    .addComponent(txtServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnRegisterService.setText("Register Service");
        btnRegisterService.addActionListener(this::btnRegisterServiceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnBack)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOwnerID)
                            .addComponent(lblOwnerFirstName)
                            .addComponent(lblOwnerLastName)
                            .addComponent(lblServiceDate))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtOwnerFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(txtOwnerID))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(VehicleArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegisterService)
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOwnerID)
                    .addComponent(txtOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerFirstName)
                    .addComponent(txtOwnerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOwnerLastName)
                    .addComponent(txtOwnerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDate)
                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(VehicleArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRegisterService)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to main interface
        Container parent = this.getParent();
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, "welcome");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterServiceActionPerformed
        // Validate all fields are not empty
        if (txtOwnerID.getText().trim().isEmpty() || 
            txtOwnerFirstName.getText().trim().isEmpty() || 
            txtOwnerLastName.getText().trim().isEmpty() || 
            txtServiceDate.getText().trim().isEmpty() ||
            txtVehicleID.getText().trim().isEmpty() ||
            txtMake.getText().trim().isEmpty() ||
            txtModel.getText().trim().isEmpty() ||
            txtRegistration.getText().trim().isEmpty() ||
            txtServiceOpted.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "All fields are required and cannot be empty!", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Get and validate owner information
            int ownerId = Integer.parseInt(txtOwnerID.getText().trim());
            String firstName = txtOwnerFirstName.getText().trim();
            String lastName = txtOwnerLastName.getText().trim();
            
            // Parse service date (format: yyyy-MM-dd)
            LocalDate serviceDate;
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                serviceDate = LocalDate.parse(txtServiceDate.getText().trim(), formatter);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, 
                    "Date format error! Please use format: yyyy-MM-dd\nExample: 2024-01-15", 
                    "Date Format Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Get and validate vehicle information
            String vehicleId = txtVehicleID.getText().trim();
            String make = txtMake.getText().trim();
            String model = txtModel.getText().trim();
            String registrationNo = txtRegistration.getText().trim();
            int serviceId = Integer.parseInt(txtServiceOpted.getText().trim());
            
            // Validate vehicle ID does not already exist
            if (vehicleDirectory.findVehicleById(vehicleId) != null) {
                JOptionPane.showMessageDialog(this, 
                    "Vehicle ID already exists! Please use a different ID.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Find service
            Service selectedService = serviceCatalog.findServiceById(serviceId);
            if (selectedService == null) {
                JOptionPane.showMessageDialog(this, 
                    "Service ID does not exist! Please create service first or use a valid service ID.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create owner object
            Owner owner = new Owner(ownerId, firstName, lastName, serviceDate);
            
            // Create vehicle object (use current year as default)
            int currentYear = LocalDate.now().getYear();
            Vehicle vehicle = new Vehicle(vehicleId, make, model, currentYear, registrationNo, owner, selectedService);
            
            // Add to vehicle directory
            vehicleDirectory.addVehicle(vehicle);
            
            // Display success message
            JOptionPane.showMessageDialog(this, 
                "Vehicle and owner registered successfully!\n" +
                "Owner: " + owner.toString() + "\n" +
                "Vehicle: " + vehicle.toString() + "\n" +
                "Service: " + selectedService.toString(), 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear form
            clearForm();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please enter valid number format!\n" +
                "Owner ID: integer\n" +
                "Service ID: integer", 
                "Input Format Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterServiceActionPerformed
    
    /**
     * Clear form
     */
    private void clearForm() {
        txtOwnerID.setText("");
        txtOwnerFirstName.setText("");
        txtOwnerLastName.setText("");
        txtServiceDate.setText("");
        txtVehicleID.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtRegistration.setText("");
        txtServiceOpted.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VehicleArea;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerFirstName;
    private javax.swing.JLabel lblOwnerID;
    private javax.swing.JLabel lblOwnerLastName;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblVehicleID;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerFirstName;
    private javax.swing.JTextField txtOwnerID;
    private javax.swing.JTextField txtOwnerLastName;
    private javax.swing.JTextField txtRegistration;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtServiceOpted;
    private javax.swing.JTextField txtVehicleID;
    // End of variables declaration//GEN-END:variables
}
