/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Vehicle;
import model.VehicleDirectory;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class VehicleListPanel extends javax.swing.JPanel {

    private VehicleDirectory vehicleDirectory;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form VehicleListPanel
     */
    public VehicleListPanel() {
        initComponents();
        vehicleDirectory = VehicleDirectory.getInstance();
        setupTable();
        loadAllVehicles();
    }
    
    /**
     * Setup table
     */
    private void setupTable() {
        tableModel = (DefaultTableModel) tblManageVehicles.getModel();
        // Clear default data
        tableModel.setRowCount(0);
    }
    
    /**
     * Load all vehicles to table
     */
    private void loadAllVehicles() {
        tableModel.setRowCount(0);
        List<Vehicle> vehicles = vehicleDirectory.getAllVehicles();
        for (Vehicle vehicle : vehicles) {
            Object[] row = new Object[4];
            row[0] = vehicle.getOwner().getOwnerId();
            row[1] = vehicle.getVehicleId();
            row[2] = vehicle.getSelectedService().getServiceType();
            row[3] = vehicle.getSelectedService().getCost();
            tableModel.addRow(row);
        }
    }
    
    /**
     * Load vehicles by search criteria
     */
    private void loadVehiclesBySearch(String searchText) {
        tableModel.setRowCount(0);
        
        // Try to search by ID first
        Vehicle vehicle = vehicleDirectory.findVehicleById(searchText);
        if (vehicle != null) {
            Object[] row = new Object[4];
            row[0] = vehicle.getOwner().getOwnerId();
            row[1] = vehicle.getVehicleId();
            row[2] = vehicle.getSelectedService().getServiceType();
            row[3] = vehicle.getSelectedService().getCost();
            tableModel.addRow(row);
        } else {
            // Search by make
            List<Vehicle> vehicles = vehicleDirectory.findVehiclesByMake(searchText);
            if (vehicles.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "No matching vehicles found!", 
                    "Search Result", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Vehicle v : vehicles) {
                    Object[] row = new Object[4];
                    row[0] = v.getOwner().getOwnerId();
                    row[1] = v.getVehicleId();
                    row[2] = v.getSelectedService().getServiceType();
                    row[3] = v.getSelectedService().getCost();
                    tableModel.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageVehicles = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setText("Manage Vehicles");

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnBack.setText("<< Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblManageVehicles.setBackground(new java.awt.Color(153, 153, 255));
        tblManageVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Owner ID", "Vehicle ID", "Service Opted", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageVehicles);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(this::btnViewDetailsActionPerformed);

        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(this::btnDeleteAccountActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearch)))
                                .addGap(18, 18, 18)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnBack))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnViewDetails)
                .addGap(46, 46, 46)
                .addComponent(btnDeleteAccount)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // Get selected row
        int selectedRow = tblManageVehicles.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a vehicle first!", 
                "Notice", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get vehicle ID
        String vehicleId = tableModel.getValueAt(selectedRow, 1).toString();
        Vehicle vehicle = vehicleDirectory.findVehicleById(vehicleId);
        
        if (vehicle != null) {
            // Display vehicle details and allow update
            showVehicleDetails(vehicle);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        // Get selected row
        int selectedRow = tblManageVehicles.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a vehicle first!", 
                "Notice", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get vehicle ID
        String vehicleId = tableModel.getValueAt(selectedRow, 1).toString();
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete vehicle " + vehicleId + "?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = vehicleDirectory.removeVehicle(vehicleId);
            if (success) {
                JOptionPane.showMessageDialog(this, 
                    "Vehicle deleted successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                // Refresh table
                loadAllVehicles();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Deletion failed!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = txtSearch.getText().trim();
        if (searchText.isEmpty()) {
            // If search box is empty, display all vehicles
            loadAllVehicles();
        } else {
            // Search by ID or make
            loadVehiclesBySearch(searchText);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to main interface
        Container parent = this.getParent();
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, "welcome");
    }//GEN-LAST:event_btnBackActionPerformed
    
    /**
     * Display vehicle details and allow update
     */
    private void showVehicleDetails(Vehicle vehicle) {
        // Create input dialog to display details
        String details = "Vehicle Details:\n\n" +
                        "Vehicle ID: " + vehicle.getVehicleId() + "\n" +
                        "Make: " + vehicle.getMake() + "\n" +
                        "Model: " + vehicle.getModel() + "\n" +
                        "Year: " + vehicle.getYear() + "\n" +
                        "Registration Number: " + vehicle.getRegistrationNo() + "\n\n" +
                        "Owner Information:\n" +
                        "Owner ID: " + vehicle.getOwner().getOwnerId() + "\n" +
                        "Name: " + vehicle.getOwner().getFirstName() + " " + vehicle.getOwner().getLastName() + "\n" +
                        "Service Date: " + vehicle.getOwner().getServiceDate() + "\n\n" +
                        "Service Information:\n" +
                        "Service ID: " + vehicle.getSelectedService().getServiceId() + "\n" +
                        "Service Type: " + vehicle.getSelectedService().getServiceType() + "\n" +
                        "Cost: $" + vehicle.getSelectedService().getCost() + "\n" +
                        "Mechanic: " + vehicle.getSelectedService().getMechanicName() + "\n" +
                        "Service Duration: " + vehicle.getSelectedService().getServiceHours() + " hours";
        
        JOptionPane.showMessageDialog(this, details, "Vehicle Details", JOptionPane.INFORMATION_MESSAGE);
        
        // Ask if user wants to update information
        int update = JOptionPane.showConfirmDialog(this, 
            "Do you want to update vehicle information?", 
            "Update Confirmation", 
            JOptionPane.YES_NO_OPTION);
        
        if (update == JOptionPane.YES_OPTION) {
            updateVehicleInfo(vehicle);
        }
    }
    
    /**
     * Update vehicle information
     */
    private void updateVehicleInfo(Vehicle vehicle) {
        // Create input dialogs
        String newMake = JOptionPane.showInputDialog(this, "Enter new make:", vehicle.getMake());
        if (newMake == null || newMake.trim().isEmpty()) return;
        
        String newModel = JOptionPane.showInputDialog(this, "Enter new model:", vehicle.getModel());
        if (newModel == null || newModel.trim().isEmpty()) return;
        
        String newRegNo = JOptionPane.showInputDialog(this, "Enter new registration number:", vehicle.getRegistrationNo());
        if (newRegNo == null || newRegNo.trim().isEmpty()) return;
        
        // Update vehicle information
        vehicle.setMake(newMake.trim());
        vehicle.setModel(newModel.trim());
        vehicle.setRegistrationNo(newRegNo.trim());
        
        JOptionPane.showMessageDialog(this, 
            "Vehicle information updated successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Refresh table
        loadAllVehicles();
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageVehicles;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
