/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.SupplierReport;
import TheBusiness.Supplier.SupplierSummary;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageBusinessDetail1 extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    String reportType;

    public ManageBusinessDetail1(Business bz, JPanel jp, String reportType) {
        CardSequencePanel = jp;
        this.business = bz;
        this.reportType = reportType;
        initComponents();
        
        // Load report data based on selected type
        loadReportData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollPaneReport = new javax.swing.JScrollPane();
        tableReportData = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Business Performance Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 550, -1));

        tableReportData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPaneReport.setViewportView(tableReportData);

        add(scrollPaneReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 560, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollPaneReport;
    private javax.swing.JTable tableReportData;
    // End of variables declaration//GEN-END:variables

    // Business logic methods
    public void refreshTable() {

    }
    
    private void loadReportData() {
        if (reportType == null) {
            return;
        }
        
        if (reportType.equals("Most Expensive Product")) {
            loadMostExpensiveProductReport();
        } else if (reportType.equals("Most Valuable Customers")) {
            loadMostValuableCustomersReport();
        } else if (reportType.equals("Supplier Report")) {
            loadSupplierReport();
        }
    }
    
    private void loadMostExpensiveProductReport() {
        // Set table column names
        String[] columnNames = {"No.", "Product Name", "Supplier Name", "Product Price"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        // Get data
        ArrayList<Product> products = business.getMostExpensiveProducts();
        
        // Fill data
        int index = 1;
        for (Product product : products) {
            Object[] row = {
                index++,
                product.getName(),
                product.getSupplier() != null ? product.getSupplier().getName() : "N/A",
                product.getTargetPrice()
            };
            model.addRow(row);
        }
        
        // Update table
        tableReportData.setModel(model);
    }
    
    private void loadMostValuableCustomersReport() {
        // Set table column names
        String[] columnNames = {"No.", "Customer Name", "Total Sales Amount"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        // Get data
        ArrayList<CustomerProfile> customers = business.getMostValuableCustomers();
        
        // Fill data
        int index = 1;
        for (CustomerProfile customer : customers) {
            Object[] row = {
                index++,
                customer.getCustomerName(),
                customer.getTotalSalesAmount()
            };
            model.addRow(row);
        }
        
        // Update table
        tableReportData.setModel(model);
    }
    
    private void loadSupplierReport() {
        // Set table column names
        String[] columnNames = {
            "Supplier Name", 
            "Total Sales", 
            "Loyalty Score", 
            "Avg Spend/Customer", 
            "Top 5 Sales Share"
        };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        // Get data
        SupplierReport report = business.getSupplierAnalysisReport();
        
        // Fill data
        for (SupplierSummary summary : report.getSummaries()) {
            Object[] row = {
                summary.getSupplierName(),
                summary.getTotalSalesVolume(),
                String.format("%.4f", summary.getLoyaltyScore()),
                String.format("%.2f", summary.getAverageSpendPerCustomer()),
                String.format("%.2f%%", summary.getTopFiveSalesShare() * 100)
            };
            model.addRow(row);
        }
        
        // Update table
        tableReportData.setModel(model);
    }

}
