/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Administrator
 */
public class CreateBankAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccount
     */
    public CreateBankAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBranchName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        fieldAccountNumber = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldBranchName = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setText("Create Bank Address");

        lblAccountNumber.setText("Account Number");

        lblBankName.setText("Bank Name");

        lblBranchName.setText("Branch Name");

        lblAccountType.setText("Account Type");

        lblBalance.setText("Balance");

        fieldBranchName.addActionListener(this::fieldBranchNameActionPerformed);

        btnsave.setText("save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAccountNumber)
                                    .addComponent(lblBankName)
                                    .addComponent(lblBranchName)
                                    .addComponent(lblAccountType)
                                    .addComponent(lblBalance))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnsave)))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(fieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranchName)
                    .addComponent(fieldBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountType)
                    .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBranchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBranchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBranchNameActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // Step 1: Obtain input values
        String accountNumberStr = fieldAccountNumber.getText().trim();
        String bankName = fieldBankName.getText().trim();
        String branchName = fieldBranchName.getText().trim();
        String accountType = fieldAccountType.getText().trim();
        String balanceStr = fieldBalance.getText().trim();
        
        // Step 2: Verify required fields
        if (accountNumberStr.isEmpty() || bankName.isEmpty() || branchName.isEmpty() || 
            accountType.isEmpty() || balanceStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "All fields are required, please fill in completely!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 3: Verify data type
        long accountNumber;
        try {
            accountNumber = Long.parseLong(accountNumberStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Account number must be a valid number!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 4: Verify data type
        double balance;
        try {
            balance = Double.parseDouble(balanceStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Balance must be a valid number!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 5: Create object
        model.BankAccount account = new model.BankAccount();
        account.setAccountNumber(accountNumber);
        account.setBankName(bankName);
        account.setBranchName(branchName);
        account.setAccountType(accountType);
        account.setBalance(balance);
        
        // Step 6: Save to the global list
        MainFrame.bankAccountList.add(account);
        
        // Step 7: Clear the input boxes
        fieldAccountNumber.setText("");
        fieldBankName.setText("");
        fieldBranchName.setText("");
        fieldAccountType.setText("");
        fieldBalance.setText("");
        
        // Step 8: Prompt success
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Bank account saved successfully!", 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBranchName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBranchName;
    // End of variables declaration//GEN-END:variables
}
