/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Administrator
 */
public class CreatePersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    public CreatePersonPanel() {
        initComponents();
        
       
        if (MainFrame.homeAddressList.isEmpty() || 
            MainFrame.localAddressList.isEmpty() || 
            MainFrame.bankAccountList.isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please create the home address, local address and bank account first!\n" +
                "Current status:\n" +
                "Home address: " + MainFrame.homeAddressList.size() + "entries\n" +
                "Local address: " + MainFrame.localAddressList.size() + "entries\n" +
                "Bank account: " + MainFrame.bankAccountList.size() + "entries", 
                "Warning", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblMaritalstatus = new javax.swing.JLabel();
        fieldMaritalstatus = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblAge.setText("Age");

        fieldAge.addActionListener(this::fieldAgeActionPerformed);

        lblMaritalstatus.setText("Marital status ");

        btnsave.setText("save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel8.setText("Create a Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge)
                            .addComponent(lblMaritalstatus)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldMaritalstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(fieldAge)
                            .addComponent(fieldLastName)
                            .addComponent(fieldFirstName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel8)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMaritalstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaritalstatus))
                .addGap(37, 37, 37)
                .addComponent(btnsave)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        //  Step 1: Obtain basic information 
        String firstName = fieldFirstName.getText().trim();
        String lastName = fieldLastName.getText().trim();
        String ageStr = fieldAge.getText().trim();
        String maritalStatusStr = fieldMaritalstatus.getText().trim();
        
        //  Step 2: Verify basic information
        if (firstName.isEmpty() || lastName.isEmpty() || ageStr.isEmpty() || maritalStatusStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "All fields are required!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        
        // Verify marital status input 
        boolean isMarried;
        if (maritalStatusStr.equalsIgnoreCase("married") || 
            maritalStatusStr.equalsIgnoreCase("yes")) {
            isMarried = true;
        } else if (maritalStatusStr.equalsIgnoreCase("single") ||
                   maritalStatusStr.equalsIgnoreCase("no")) {
            isMarried = false;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please enter marital status: Married/Single ", 
                "Input error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 3: Check for available associated objects
        if (MainFrame.homeAddressList.isEmpty() || 
            MainFrame.localAddressList.isEmpty() || 
            MainFrame.bankAccountList.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please create the home address, local address and bank account first!", 
                "Unable to save!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 4: Create a Person object and set basic attributes
        model.Person person = new model.Person();
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setMarried(isMarried);
        
        // Step 5: Automatically associate the first address and account
        // Obtain the first home address
        model.Address homeAddress = MainFrame.homeAddressList.get(0);
        person.setHomeAddress(homeAddress);
        
        // Obtain the first local address
        model.Address localAddress = MainFrame.localAddressList.get(0);
        person.setLocalAddress(localAddress);
        
        // Obtain the first bank account
        model.BankAccount bankAccount = MainFrame.bankAccountList.get(0);
        person.setBankAccount(bankAccount);
        
        //Step 6: Save to the global list
        MainFrame.personList.add(person);
        
        // Step 7: Clear the input boxes
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldAge.setText("");
        fieldMaritalstatus.setText("");
        
        // Step 8: Prompt success
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Personal information saved successfully!\n" +
            "Automatically associated:\n" +
            "- Home address: " + homeAddress.getCity() + "\n" +
            "- Local address: " + localAddress.getCity() + "\n" +
            "- Bank account: " + bankAccount.getBankName(), 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldMaritalstatus;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalstatus;
    // End of variables declaration//GEN-END:variables
}
