/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Administrator
 */
public class CreateHomeAddress extends javax.swing.JPanel {

    /**
     * Creates new form CreateHomeAddress
     */
    public CreateHomeAddress() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblPostalCode = new javax.swing.JLabel();
        lblHouseNumber = new javax.swing.JLabel();
        fieldCountry = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        fieldPostalCode = new javax.swing.JTextField();
        fieldHouseNumber = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setText("Create Home Address");

        lblCountry.setText("Country");

        lblCity.setText("City");

        lblStreet.setText("Street");

        lblPostalCode.setText("Postal Code");

        lblHouseNumber.setText("House Number");

        fieldStreet.addActionListener(this::fieldStreetActionPerformed);

        btnsave.setText("save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCountry)
                                    .addComponent(lblCity)
                                    .addComponent(lblStreet)
                                    .addComponent(lblPostalCode)
                                    .addComponent(lblHouseNumber))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnsave)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(fieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(fieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode)
                    .addComponent(fieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseNumber)
                    .addComponent(fieldHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // Step 1: Obtain input values and remove spaces
        String country = fieldCountry.getText().trim();
        String city = fieldCity.getText().trim();
        String street = fieldStreet.getText().trim();
        String postalCode = fieldPostalCode.getText().trim();
        String houseNumberStr = fieldHouseNumber.getText().trim();
        
        // Step 2: Verify required fields (empty value check)
        if (country.isEmpty() || city.isEmpty() || street.isEmpty() || 
            postalCode.isEmpty() || houseNumberStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "All fields are required, please fill in completely!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 3: Verify data type
        int houseNumber;
        try {
            houseNumber = Integer.parseInt(houseNumberStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "House number must be a valid integer!", 
                "Input error!", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Step 4: Create Address object and assign values
        model.Address address = new model.Address();
        address.setCountry(country);
        address.setCity(city);
        address.setStreet(street);
        address.setPostalCode(postalCode);
        address.setHouseNumber(houseNumber);
        
        // Step 5: Save to the global list
        MainFrame.homeAddressList.add(address);
        
        // Step 6: Clear the input boxes
        fieldCountry.setText("");
        fieldCity.setText("");
        fieldStreet.setText("");
        fieldPostalCode.setText("");
        fieldHouseNumber.setText("");
        
        // Step 7: Prompt success
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Home address saved successfully!", 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCountry;
    private javax.swing.JTextField fieldHouseNumber;
    private javax.swing.JTextField fieldPostalCode;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblStreet;
    // End of variables declaration//GEN-END:variables
}
