/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Administrator
 */
public class ViewPersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPersonPanel() {
        initComponents();
        
        // 加载数据
        loadData();
    }
    
    /**
     * 加载Person数据并展示关联信息
     */
    private void loadData() {
        // ========== 第一步：检查列表是否为空 ==========
        if (MainFrame.personList.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "暂无个人信息数据，请先创建！", 
                "提示", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // 清空所有字段
            clearAllFields();
            return;
        }
        
        // ========== 第二步：读取第一个Person对象 ==========
        model.Person person = MainFrame.personList.get(0);
        
        // ========== 第三步：填充基本信息 ==========
        fieldFirstName.setText(person.getFirstName());
        fieldLastName.setText(person.getLastName());
        fieldAge.setText(String.valueOf(person.getAge()));
        fieldMaritalstatus.setText(person.isMarried() ? "已婚" : "未婚");
        
        // ========== 第四步：设置所有字段为只读 ==========
        fieldFirstName.setEditable(false);
        fieldLastName.setEditable(false);
        fieldAge.setEditable(false);
        fieldMaritalstatus.setEditable(false);
        
        // ========== 第五步：在控制台输出关联信息（用于验证1对1关联） ==========
        System.out.println("\n========== 个人信息详情 ==========");
        System.out.println("姓名: " + person.getLastName() + " " + person.getFirstName());
        System.out.println("年龄: " + person.getAge());
        System.out.println("婚姻状况: " + (person.isMarried() ? "已婚" : "未婚"));
        
        // 展示关联的家庭地址（1对1关联展示）
        if (person.getHomeAddress() != null) {
            System.out.println("\n家庭地址信息:");
            System.out.println(person.getHomeAddress().toString());
        } else {
            System.out.println("\n家庭地址: 未关联");
        }
        
        // 展示关联的本地地址（1对1关联展示）
        if (person.getLocalAddress() != null) {
            System.out.println("\n本地地址信息:");
            System.out.println(person.getLocalAddress().toString());
        } else {
            System.out.println("\n本地地址: 未关联");
        }
        
        // 展示关联的银行账户（1对1关联展示）
        if (person.getBankAccount() != null) {
            System.out.println("\n银行账户信息:");
            System.out.println(person.getBankAccount().toString());
        } else {
            System.out.println("\n银行账户: 未关联");
        }
        
        System.out.println("================================\n");
        
        // ========== 第六步：弹窗显示完整信息（包含关联对象） ==========
        StringBuilder message = new StringBuilder();
        message.append("姓名: ").append(person.getLastName()).append(" ").append(person.getFirstName()).append("\n");
        message.append("年龄: ").append(person.getAge()).append("\n");
        message.append("婚姻状况: ").append(person.isMarried() ? "已婚" : "未婚").append("\n\n");
        
        if (person.getHomeAddress() != null) {
            message.append("家庭地址:\n").append(person.getHomeAddress().toString()).append("\n\n");
        }
        
        if (person.getLocalAddress() != null) {
            message.append("本地地址:\n").append(person.getLocalAddress().toString()).append("\n\n");
        }
        
        if (person.getBankAccount() != null) {
            message.append("银行账户:\n").append(person.getBankAccount().toString());
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            message.toString(), 
            "个人信息详情（含关联信息）", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * 清空所有字段
     */
    private void clearAllFields() {
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldAge.setText("");
        fieldMaritalstatus.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldMaritalstatus = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblMaritalstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel8.setText("View a Product");

        lblLastName.setText("Last Name");

        lblAge.setText("Age");

        lblFirstName.setText("First Name");

        fieldAge.addActionListener(this::fieldAgeActionPerformed);

        lblMaritalstatus.setText("Marital status ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge)
                            .addComponent(lblMaritalstatus)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldMaritalstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(fieldAge)
                            .addComponent(fieldLastName)
                            .addComponent(fieldFirstName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel8)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaritalstatus)
                    .addComponent(fieldMaritalstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldMaritalstatus;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalstatus;
    // End of variables declaration//GEN-END:variables
}
